# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-17 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle_platform', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadrecord',
            name='upload_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
