# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-18 03:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle_platform', '0002_auto_20180717_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadrecord',
            name='upload_game',
            field=models.IntegerField(choices=[(0, 'Royal war'), (1, 'None')], default=0),
        ),
    ]
