# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-18 08:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('battle_platform', '0003_auto_20180718_0309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadrecord',
            name='replay',
        ),
    ]
